# Generated by Django 2.2.5 on 2019-10-02 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for an area', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the area name', max_length=50)),
                ('priority', models.IntegerField(help_text='Enter area priority. 0 = low')),
                ('dcr', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('ucr', models.CharField(help_text='Creation user', max_length=50)),
                ('dlm', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('ulm', models.CharField(help_text='Last modification user', max_length=50)),
            ],
            options={
                'ordering': ['site_id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a client', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of your organisation', max_length=50)),
                ('priority', models.IntegerField(help_text='Enter client priority. 0 = low')),
                ('country', models.CharField(help_text='3 digit country code', max_length=3)),
                ('address_line_1', models.CharField(help_text='Enter address information here', max_length=50)),
                ('address_line_2', models.CharField(help_text='Enter address information here', max_length=50)),
                ('address_line_3', models.CharField(help_text='Enter address information here', max_length=50)),
                ('address_line_4', models.CharField(help_text='Enter address information here', max_length=50)),
                ('dcr', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('ucr', models.CharField(help_text='Creation user', max_length=50)),
                ('dlm', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('ulm', models.CharField(help_text='Last modification user', max_length=50)),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a component', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the component name', max_length=50)),
                ('priority', models.IntegerField(help_text='Enter component priority. 0 = low')),
                ('golive', models.DateTimeField(help_text='Enter first usage of the component')),
                ('dcr', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('ucr', models.CharField(help_text='Creation user', max_length=50)),
                ('dlm', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('ulm', models.CharField(help_text='Last modification user', max_length=50)),
            ],
            options={
                'ordering': ['system_id'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a system', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the system name', max_length=50)),
                ('priority', models.IntegerField(help_text='Enter system priority. 0 = low')),
                ('dcr', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('ucr', models.CharField(help_text='Creation user', max_length=50)),
                ('dlm', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('ulm', models.CharField(help_text='Last modification user', max_length=50)),
                ('area_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='millenniumfalcon.Area')),
            ],
            options={
                'ordering': ['area_id'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a site', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of your site', max_length=50)),
                ('priority', models.IntegerField(help_text='Enter site priority. 0 = low')),
                ('country', models.CharField(help_text='3 digit country code', max_length=3)),
                ('address_line_1', models.CharField(help_text='Enter address information here', max_length=50)),
                ('address_line_2', models.CharField(help_text='Enter address information here', max_length=50)),
                ('address_line_3', models.CharField(help_text='Enter address information here', max_length=50)),
                ('address_line_4', models.CharField(help_text='Enter address information here', max_length=50)),
                ('dcr', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('ucr', models.CharField(help_text='Creation user', max_length=50)),
                ('dlm', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('ulm', models.CharField(help_text='Last modification user', max_length=50)),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='millenniumfalcon.Client')),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a mission', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the mission name', max_length=50)),
                ('priority', models.IntegerField(help_text='Enter mission priority. 0 = low')),
                ('short_desc', models.CharField(help_text='Enter short description of the mission', max_length=200)),
                ('instruction', models.TextField(help_text='Enter detailed instructions for the mission', max_length=1000)),
                ('mission_type', models.CharField(blank=True, choices=[('p', 'PPM'), ('r', 'REPAIR'), ('c', 'CHECK')], default='c', help_text='Mission type', max_length=1)),
                ('status', models.CharField(blank=True, choices=[('p', 'PPM'), ('r', 'REPAIR'), ('c', 'CHECK')], default='i', help_text='Mission status', max_length=1)),
                ('last_execution', models.DateTimeField()),
                ('last_duration', models.CharField(help_text='Enter last duration', max_length=10)),
                ('planned_duration', models.CharField(help_text='Enter planned duration', max_length=10)),
                ('execution_interval', models.IntegerField(help_text='mission execution interval')),
                ('KPI_reference', models.CharField(help_text='Enter KPI', max_length=10)),
                ('dcr', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('ucr', models.CharField(help_text='Creation user', max_length=50)),
                ('dlm', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('ulm', models.CharField(help_text='Last modification user', max_length=50)),
                ('component_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='millenniumfalcon.Component')),
            ],
            options={
                'ordering': ['component_id', 'status'],
            },
        ),
        migrations.AddField(
            model_name='component',
            name='system_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='millenniumfalcon.System'),
        ),
        migrations.AddField(
            model_name='area',
            name='site_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='millenniumfalcon.Site'),
        ),
    ]
