# Generated by Django 2.2.5 on 2019-10-03 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('millenniumfalcon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='next_due',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enter (calculate) next due date'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='last_execution',
            field=models.DateTimeField(help_text='Enter last execution date'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a Task', primary_key=True, serialize=False)),
                ('assigned_user', models.CharField(help_text='Assigned User', max_length=50)),
                ('status', models.CharField(blank=True, choices=[('c', 'CREATED'), ('p', 'PLANNED'), ('a', 'ACTIVE'), ('f', 'FINISHED'), ('d', 'DEFERRED')], default='i', help_text='Mission status', max_length=1)),
                ('planned_start', models.DateTimeField(default=django.utils.timezone.now, help_text='Planned time of task execution')),
                ('act_start', models.DateTimeField(default=django.utils.timezone.now, help_text='Task beginning timestamp')),
                ('act_end', models.DateTimeField(default=django.utils.timezone.now, help_text='Task ending timestamp')),
                ('comment', models.CharField(help_text='Engineers comment', max_length=50)),
                ('dcr', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('ucr', models.CharField(help_text='Creation user', max_length=50)),
                ('dlm', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('ulm', models.CharField(help_text='Last modification user', max_length=50)),
                ('mission_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='millenniumfalcon.Mission')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
