# Generated by Django 2.2.5 on 2019-10-04 09:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('millenniumfalcon', '0003_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(blank=True, choices=[('i', 'IDLE'), ('a', 'ACTIVE'), ('p', 'PAUSED')], default='i', help_text='Mission status', max_length=1),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a mission', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('c', 'CREATED'), ('p', 'PLANNED'), ('a', 'ACTIVE'), ('d', 'DEFERRED'), ('f', 'FINISHED')], default='c', help_text='Task status', max_length=1)),
                ('actual_start', models.DateTimeField(default='', help_text='Actual start timestamp of the task execution', null=True)),
                ('remark', models.CharField(help_text='Remark from execution user', max_length=200)),
                ('dcr', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('ucr', models.CharField(help_text='Creation user', max_length=50)),
                ('dlm', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('ulm', models.CharField(help_text='Last modification user', max_length=50)),
                ('mission_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='millenniumfalcon.Mission')),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
