# Generated by Django 2.2.5 on 2019-10-06 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('millenniumfalcon', '0004_auto_20191004_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enter (calculate) next due date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('c', 'CREATED'), ('p', 'PLANNED'), ('s', 'STARTED'), ('d', 'DEFERRED'), ('f', 'FINISHED')], default='c', help_text='Task status', max_length=1),
        ),
    ]
