# Generated by Django 2.2.5 on 2019-10-06 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('millenniumfalcon', '0005_auto_20191006_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_start',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enter planned starting timestamp'),
        ),
    ]
