# Generated by Django 2.2.5 on 2019-11-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('millenniumfalcon', '0006_task_planned_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='system_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='millenniumfalcon.System'),
        ),
    ]
