# Generated by Django 2.2.5 on 2019-11-08 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('millenniumfalcon', '0007_auto_20191108_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='site_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='millenniumfalcon.Site'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='component_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='millenniumfalcon.Component'),
        ),
        migrations.AlterField(
            model_name='site',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='millenniumfalcon.Client'),
        ),
        migrations.AlterField(
            model_name='system',
            name='area_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='millenniumfalcon.Area'),
        ),
    ]
