# Generated by Django 2.2.5 on 2020-01-06 11:49

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('millenniumfalcon', '0008_auto_20191108_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for a supplier', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the Supplier name', max_length=50)),
                ('country', models.CharField(help_text='3 digit country code', max_length=3)),
                ('address_line_1', models.CharField(help_text='Enter address information here', max_length=50)),
                ('address_line_2', models.CharField(blank=True, help_text='Enter address information here', max_length=50)),
                ('address_line_3', models.CharField(blank=True, help_text='Enter address information here', max_length=50)),
                ('address_line_4', models.CharField(blank=True, help_text='Enter address information here', max_length=50)),
                ('dcr', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('ucr', models.CharField(default='Creation user', help_text='Creation user', max_length=50)),
                ('dlm', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('ulm', models.CharField(default='Last modification user', help_text='Last modification user', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='area',
            name='ucr',
            field=models.CharField(default='Creation user', help_text='Creation user', max_length=50),
        ),
        migrations.AlterField(
            model_name='area',
            name='ulm',
            field=models.CharField(default='Creation user', help_text='Last modification user', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Enter address information here', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_line_3',
            field=models.CharField(blank=True, help_text='Enter address information here', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_line_4',
            field=models.CharField(blank=True, help_text='Enter address information here', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='ucr',
            field=models.CharField(default='Creation user', help_text='Creation user', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='ulm',
            field=models.CharField(default='Creation user', help_text='Last modification user', max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='golive',
            field=models.DateTimeField(auto_now_add=True, help_text='Enter first usage of the component'),
        ),
        migrations.AlterField(
            model_name='component',
            name='ucr',
            field=models.CharField(default='Creation user', help_text='Creation user', max_length=50),
        ),
        migrations.AlterField(
            model_name='component',
            name='ulm',
            field=models.CharField(default='Creation user', help_text='Last modification user', max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='KPI_reference',
            field=models.CharField(blank=True, help_text='Enter KPI', max_length=10),
        ),
        migrations.AlterField(
            model_name='mission',
            name='execution_interval',
            field=models.IntegerField(blank=True, default=1, help_text='mission execution interval'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='last_duration',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Enter last duration', max_length=10),
        ),
        migrations.AlterField(
            model_name='mission',
            name='last_execution',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter last execution date'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='next_due',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enter (calculate) next due date'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='planned_duration',
            field=models.CharField(blank=True, default=django.utils.timezone.now, help_text='Enter planned duration', max_length=10),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ucr',
            field=models.CharField(blank=True, help_text='Creation user', max_length=50),
        ),
        migrations.AlterField(
            model_name='mission',
            name='ulm',
            field=models.CharField(blank=True, help_text='Last modification user', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Enter address information here', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='address_line_3',
            field=models.CharField(blank=True, help_text='Enter address information here', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='address_line_4',
            field=models.CharField(blank=True, help_text='Enter address information here', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='ucr',
            field=models.CharField(default='Creation user', help_text='Creation user', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='ulm',
            field=models.CharField(default='Creation user', help_text='Last modification user', max_length=50),
        ),
        migrations.AlterField(
            model_name='system',
            name='ucr',
            field=models.CharField(default='Creation user', help_text='Creation user', max_length=50),
        ),
        migrations.AlterField(
            model_name='system',
            name='ulm',
            field=models.CharField(default='Last modification user', help_text='Last modification user', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='actual_start',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Actual start timestamp of the task execution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='ucr',
            field=models.CharField(blank=True, help_text='Creation user', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='ulm',
            field=models.CharField(blank=True, help_text='Last modification user', max_length=50),
        ),
    ]
